//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KwikMedical.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class call_outs
    {
        public int id { get; set; }
        public int patient_id { get; set; }
        public int hospital_id { get; set; }
        public string date { get; set; }
        public string reason { get; set; }
        public string action_taken { get; set; }
        public string time_spent { get; set; }
    
        public virtual patient patient { get; set; }
        public virtual regional_hospitals regional_hospitals { get; set; }
    }
}
