//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KwikMedical.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class regional_hospitals
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public regional_hospitals()
        {
            this.patients = new HashSet<patient>();
            this.call_outs = new HashSet<call_outs>();
        }
    
        public int id { get; set; }
        public string hospital_name { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public int phone_number { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<patient> patients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<call_outs> call_outs { get; set; }
    }
}
